# This is a basic workflow to help you get started with Actions

name: Build android apk

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      refToBuild:
        description: 'Build Android Apk'
        required: true
        type: string


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.refToBuild }}
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.3
      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK to Github Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DemoApp
          path: app/build/outputs/apk/debug/demoApp.apk
